### ISSUE TITLE
Target and comparator cohorts empty 

### ISSUE THREAD

**Issue by jepark315** [chandryou/TicagrelorVsClopidogrel#23]
I fixed what I thought to be the reason of the error but couldn't fix the error.
Do you have any ideas why target and comparator cohorts are empty in my case?
Thank you.

**Comment by chandryou** [comment]
If your center implemented ATLAS on the server, I recommend you to create cohort by loading the json file below in ATLAS

https://github.com/chandryou/TicagrelorVsClopidogrel/blob/master/inst/cohorts/SCYouHIRA_Ticagrelor_for_ACS_KOR.json

**Comment by jepark315** [comment]
But the cohorts were created well and only the target and comparator cohorts are empty. Am I missing something? Do you think it is still neccessary to create cohort in ATLAS?

**Comment by chandryou** [comment]
I recommend you to see the cohort generation flow in ATLAS because the designs for ticagrelor and clopidogrel is much more complex than those for other cohorts.

**Comment by jepark315** [comment]
I've created the cohort and the report says there's 0 population from the very beginning so how could i interpret this result? Is there anything I could do?

**Comment by chandryou** [comment]
@jepark315 
Then, you don't have any patient who passed the entry event criteria.
Entry event criteria composed of 'ticagrelor use' and 'Percutaneous Coronary Intervention' history. 
I 'm afraid of whether your institution have converted **ticagrelor** or **PCI** records into CDM. 

Or could you let me know the concept ids used for ticagrelor or PCI in your institution?

**Comment by jepark315** [comment]
I've checked and found out what caused the problem. In my institute, we haven't converted PCI records into CDM yet. So there were 0 populations. Thank you for help :) Hope to run this package soon!
